name: Build & Test

on:
  push:
    branches-ignore:
      - "main"
      - "maintenance/v*"
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and Test (Solr ${{ matrix.version.solr }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - solr: 9.6.0
            lucene: 9.10.0
          - solr: 9.7.0
            lucene: 9.11.1
          - solr: 9.8.0
            lucene: 9.11.1
            sonar: enabled
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java/Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile & Test
        run: ./mvnw -V -B --no-transfer-progress
          clean verify
          -Dsolr.version=${{matrix.version.solr}}
          -Dlucene.version=${{matrix.version.lucene}}
          -Psonarcloud
          -Dsonar.projectKey=redlink-gmbh_solr-suggest-free-text
          -Dsonar.skip=${{ github.actor == 'dependabot[bot]' || matrix.version.sonar != 'enabled' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Test-Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (Solr ${{matrix.version.solr}})
          path: '**/TEST-*.xml'

  test-results:
    name: Test Results
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Fetch Test-Results
        uses: actions/download-artifact@v5
        with:
          path: test-results
      - name: Report Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'test-results/**/TEST-*.xml'
          action_fail: 'true'
          action_fail_on_inconclusive: 'true'
